@startuml
left to right direction

node "N1 (originator)" as N1 #LightBlue
node N2 #LightBlue
node N3
node N4
node "N5 (terminus)" as N5 #LightBlue

N2 <-[#Red]- N1
N1 <-- N2 : L1
N2 <-- N3 : L2
N3 -[#Gray]- N2
N3 <-- N4 : L3
N4 -[#Gray]- N3
N4 <-- N5 : L4
N5 -[#Gray]- N4
N1 -[#Red]-> N5

note top of N1
    |= Edge |= P |
    | -L1 | <&check> |
    | L1-L2 | - |
    | L2-L3 | - |
    | L3-L4 | - |
    | L4- | - |
end note

note top of N2
    |= Edge |= P |
    | L1- | <&check> |
    | -L1 | <&check> |
    | L2-L3 | - |
    | L3-L4 | - |
    | L4- | - |
end note

note top of N5
    |= Edge |= P |
    | L1- | <&check> |
    | L1-L2 | - |
    | L2-L3 | - |
    | L3-L4 | - |
    | -L4 | <&check> |
end note

@enduml
