@startuml
left to right direction

node N1 #LightGreen
node N2 #LightGreen
node N3 #LightGreen
node N4 #LightGreen
node N5 #LightGreen

N1 -[#Gray]- N2
N1 -[#Gray]- N3
N1 -[#Gray]- N4
N1 -[#Gray]- N5
N2 -[#Gray]- N3
N2 -[#Gray]- N4
N2 -[#Gray]- N5
N3 -[#Gray]- N4
N3 -[#Gray]- N5
N4 -[#Gray]- N5


@enduml
